apiVersion: v1
kind: ConfigMap
metadata:
  name: namespace-scripts
data:
  create_namespace.sh: |
    #!/bin/bash
    set -e
    NAMESPACE="$1"
    if [ -z "$NAMESPACE" ]; then
      echo "Usage: $0 <namespace>"
      exit 1
    fi
    vault namespace create "$NAMESPACE"
    echo "Namespace '$NAMESPACE' created successfully."
  run_for_all_namespaces.sh: |
    #!/bin/bash
    set -e
    NAMESPACE_FILE="namespaces.yaml"
    if ! command -v yq &> /dev/null; then
      echo "yq is required. Install with: apk add --no-cache yq"
      exit 1
    fi
    for ns in $(yq '.namespaces[]' "$NAMESPACE_FILE" | tr -d '"'); do
      ./create_namespace.sh "$ns"
    done
  namespaces.yaml: |
    namespaces:
      - "Acme/Prod/Alpha"
      - "Acme/Dev/Beta"
      - "Globex/Prod/Gamma"
      - "Globex/Stage/Delta" 